#logging.config.classpath: "logback-console.xml"
server:
  port: "${PORT:4242}"
  servlet.context-path: "/arch-playground-spring"
  tomcat:
    accesslog:
      enabled: true
      pattern: "combined"
management:
  metrics.distribution:
      percentiles.http.server.requests: "0.95, 0.99"
      percentiles-histogram.http.server.requests: true
      sla.http.server.requests: "10ms, 100ms"
  health.diskspace.enabled: false
  endpoints.web:
    base-path: "/internal"
    exposure.include: "*"
  endpoint:
    env:
      enabled: true
    health:
      enabled: true
    loggers:
      enabled: true
    metrics:
      enabled: true
    httptrace:
      enabled: true
info:
  build:
    commit: "${edison.status.vcs.commit:}"
    version: "${edison.status.vcs.version:}"
spring:
  application.name: "arch-playground-spring"
  thymeleaf.mode: "HTML"
  jackson.default-property-inclusion: NON_NULL
edison:
  application:
    title: "arch-playground-spring"
    group: "arch"
    environment: "${GROUP:local}"
    description: "Make breuninger architecture great again."
    management.base-path: "/internal"
  status:
    redirect-internal.enabled: false
    team:
      name: "arch"
      technical-contact: "bene@breuninger.de"
      business-contact: "bene@breuninger.de"
  gracefulshutdown.enabled: false
  mongo:
    host: "localhost"
    db: "arch-playground-spring"
    maxWaitTime: 50
    connectTimeout: 150
    defaultReadTimeout: 1500
    defaultWriteTimeout: 1500
    serverSelectionTimeout: 800
    connectionpool:
      minSize: 1
      maxSize: 100
    blockedConnectionMultiplier: 2
#  metrics:
#    graphite:
#      host:  "carbon-relay.otto.nexinto.com"
#      port: 2003
  vault:
    enabled: false
    base-url: "doesnotmatter"
#    properties: "edison.mongo.user,edison.mongo.password,user.session-management.owt-validation.signature.key,user.session-management.owt-validation.uniqueUserId.key,user.session-management.lid-validation.key,user.loginRedirectTokenGenerator.key,profile.api.users.user,profile.api.users.password,externalProxy.user,externalProxy.password,social.tags.export.api.user,social.tags.export.api.password,comscore.board-report.password,comscore.board-report.user"
    token-source: "environment"
    environment-token: "VAULT_TOKEN"
#    secret-path: "${GROUP:local}/social/feed"
  ldap:
    enabled: false
    baseDn[0]: "ou=otto,ou=people,dc=lhotse,dc=otto,dc=de"
    baseDn[1]: "ou=tools,ou=people,dc=lhotse,dc=otto,dc=de"
    role-base-dn: "ou=mesos,ou=groups,dc=lhotse,dc=otto,dc=de"
    host: "ldap.lhotse.ov.otto.de"
    port: 389
    rdn-identifier: "uid"
    prefix: "/internal"
    whitelisted-paths: "/internal/health,/internal/status,/internal/jobdefinitions"
